services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.34
    restart: on-failure:2
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_CONTAINER_PORT
    volumes:
      - my-db:/var/lib/mysql

  springboot-web-tetris:
    container_name: springboot-web-tetris
    depends_on:
      - mysqldb
    build: .
    command: ./mvnw
    restart: on-failure:2
    x-develop:
      watch:
        - path: ./frontend
          action: sync
          target: /frontend
          ignore:
            - generated/
        - path: package.json
          action: rebuild
        - path: pom.xml
          action: rebuild
        - path: .env
          action: rebuild
        - path: ./src
          action: sync
          target: /src
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQL_CONTAINER_PORT/$MYSQL_DATABASE",
          "spring.datasource.username": "$MYSQL_USER",
          "spring.datasource.password": "$MYSQL_PASSWORD",
          "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
          "spring.jpa.hibernate.ddl-auto": "update"
        }'
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_CONTAINER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  my-db:
